version: "1"
services:
  - type: web
    name: flask-dashboard
    runtime: python
    repo: https://github.com/simongemmill/flask-dashboard
    branch: main
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: REDIS_URL
        fromFile: Redris.env
    autoDeploy: true
